config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  post "create-site", to: "main#create_site"
  post "update-form", to: "main#update_form"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def create_site
    GithubRepository.new(params[:repo_name], params[:data]).create

    redirect_to "https://github.com/#{Rails.application.credentials.gh_owner}?tab=repositories", allow_other_host: true, status: :see_other
  end

  def update_form
    theme = Theme.new params[:theme]

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("theme-form", partial: "forms/theme_form", locals: { theme: theme })
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forms/_theme_form.html.erb
<div id="theme-form">
  <h1><%= theme.name.titleize %> Theme</h1>

  <%= form_with url: create_site_path, builder: ThemeFormBuilder,  method: :post, html: { "data-turbo": false } do |f| %>
    <%= f.label :repo_name, "Repo Name:" %>
    <%= f.text_field :repo_name %>
    <br>
    <br>

    <% theme.fields.each do |field| %>
      <div>
        <%= f.label field["label"] %>
        <%= f.send(field["element"], "data[#{field["attribute_name"]}]", **field.except("element", "attribute_name", "label")) %>
      </div>
      <br>
    <% end %>

    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Static Site Generator Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<%= form_with url: update_form_path, method: :post do |f| %>
  <%= label_tag :theme, "Choose Theme" %>
  <%=
    select_tag :theme, options_for_select([
      [ "Green", :green ],
      [ "Red", :red ]
    ]),
    onchange: "this.form.requestSubmit()"
  %>
<% end %>
<br>
<br>
<div id="theme-form">
  <%= render partial: "forms/theme_form", locals: { theme: Theme.new("green") } %>
</div>